FROM nginx:stable-alpine
LABEL org.opencontainers.image.source="https://github.com/elvenhope/turiba-devops-labs"
LABEL org.opencontainers.image.description="Lab 1: Ship it!"
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80